### ISSUE TITLE
Wireguard starts but QR codes do not work.

### ISSUE THREAD

**Issue by The-Kid-Gid** [linuxserver/docker-wireguard#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
docker container spins up and works normally and QR codes are functional.

## Current Behavior
When I run `docker compose up -d` the logs show several problems. I'm not sure exactly what is wrong. When I scan the QR codes from the logs with my phone, my phone says: `The scanned QR code is not a valid Wireguard configuration`.

## Steps to Reproduce
1.  Run docker-compose with the following docker-compose.yml

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)     
**CPU architecture:** arm64     
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
```
wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
        ### optional ###
      - SERVERURL=mydomainname.tld
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=192.168.0.253 # pihole IP
      - INTERNAL_SUBNET=10.13.13.0 # default
    volumes:
      - ${USERDIR}/docker/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    994
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Err:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:2 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Err:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Reading package lists...
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-backports/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-security/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ppa.launchpad.net/wireguard/wireguard/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Raspbian kernel naming convention detected, attempting to install raspbian kernel headers
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
Err:1 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Err:2 http://archive.raspberrypi.org/debian buster InRelease
  Temporary failure resolving 'archive.raspberrypi.org'
Err:3 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:5 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:6 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Reading package lists...
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-backports/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-security/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease  Temporary failure resolving 'archive.raspberrypi.org'
W: Failed to fetch http://ppa.launchpad.net/wireguard/wireguard/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package raspberrypi-kernel-headers
E: Unable to locate package wireguard
Server mode is selected
External server address is set to mydomainname.tld
External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container
Internal subnet is set to 10.13.13.0
Peer DNS servers will be set to 192.168.0.253
Server mode is selected
Server related environment variables changed, regenerating 1 server and 2 peer/client confs
PEER 1 QR code:
█████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████
████ ▄▄▄▄▄ █▀▄  ▀▄▄ ▄ ██ ▀▄▀▄█▄ ▀ █▀█ █▀█▀▀▀ █ ▄▄▄▄▄ ████
████ █   █ █▄▀▀▀▀ █ ▄▀▄ █▀  ▄▀█▄ ▀▄▄ ██ █▀█ ▄█ █   █ ████
████ █▄▄▄█ █ █ █ █   ▄▄▀█▄ ▄▄▄  ▀██   █▀ ▀▀███ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ ▀ █▄█ █▄▀ ▀ ▀ █▄█ ▀ █▄▀▄█ ▀▄▀▄█▄█▄▄▄▄▄▄▄████
████▄▄▀▄▀█▄▄▀▄▄▀ ▄█▀▄  ▄ ▀ ▄   ▀ ▄▀▀█▀█▀ ▀ ▄█▀▄▄ █▄▄█████
████ ███▀▄▄█▀ █ █▀█▄█▄▀▀█ ██▄  ▀██▄▀  ▄ ▄▀ █▄█▄▀ ██▄ ████
████▀▀▀█▄█▄█▀█▀ █▄█   █▄▄   █▀▀▄▀▀▄██▄▄▀█▀▄ ▀▄▄▄ █▀▄ ████
█████▄  █▀▄█▄█▀▄ ▄▀ ▄██ █▀█▄▀▀▄▄█▄█ ▀█▄▄▄▄█▀▄▄█▀▄ ▀▀ ████
████▀██▄▄▀▄█ ▀ ▀▄ ▄   █▄▄▀█▄▀▄▄▄ ▀▀ ▀█ ▄ ▄▀▀█▀▀▀▄▄█ ▀████
████▀▀██▀▀▄█▄█▄▀▀▀▄▄ █▄▀▄  ▀▄▄██▄ ▀█  █▄▄▀ ▀▀▄█▄▄▄ ▀█████
████ ▄▄█  ▄ ▄  ▀ ███ ▄▄█▀ █▀█ ▄██▀▄▄▄   ██▄▀█▄▄██ █▀ ████
█████ ▄█ ▄▄▄ ▀ ▄██ █ ██▄█▄ ▄▄▄ ▀█ █▀ █▄▀ █ ▄ ▄▄▄ ▀▄ ▄████
█████▄   █▄█ █▄▀  █▀██▀ ▄  █▄█ ▀▄▄█▀ ██▀▀▀█▀ █▄█ ▀ █▀████
█████▀▀▀▄ ▄▄  ▄ ▄  ▀▄▀▀ ▀▄▄ ▄ ▄▀▄▀███▄▄█▄▄█    ▄ ██  ████
████ █▀▄█ ▄▄▀ ▄▄ ▀▀ █▄█  ▀▀█▄▀ ▄█▄ ▄▀▄▀▀ ▀ ▄▄▄ ▄█▀▄▄▄████
█████▀█▄█ ▄█▄▀▄▄▄█▄  █▀█▄▀▀ ███████▄▀  ██▀▄████▀█▄█▄ ████
████▄▄▄▄█ ▄▀▄▀█▄▄▀ ▀▀  ▄▀▄ ▄▀▀▀█ ▄██▀ ▀  █ ██▀▄▄█▄▄▄█████
█████▀█ █▄▄▀▀▄▄  ▄ ▀█▀▄▀ ▄█▀▄▀█▄▀ ▄ ▄▀ ▄▄█▀▀█  █ █▄█▀████
████ ▀▀█  ▄ ▀ ██ ▀▄█▄█▄█▀█▀█▀█▄█▀▄ ▀▄ ▄██ ▄█    ▄▀▀▄▄████
█████ ▀▀█▄▄▄▄██▄▀▄██▀ ▄▀█▀▄ █▄▄ ▄▄▄ █▀▄ ▄███▀▀▀██▀██▄████
████▄▄▄███▄▄   ██  ▄█▄▀ ▄█ ▄▄▄ ██▀█▄█▄▄█▀▄██ ▄▄▄ ▀█▄▄████
████ ▄▄▄▄▄ █▄▄▀██▄▀▄  ▀▀▄█ █▄█ ▄ █ ▀▄▄ ▄ ███ █▄█ ▄  ▀████
████ █   █ █▀▄ ▀▄ ▄ ▄▀█▀█▄  ▄ ▄███ █▄▄ ▄▀█▀▀▄ ▄  ▀██▄████
████ █▄▄▄█ █▀▄▄▄▄█▄ █▄▄▀▀▀█▄█▀▀██ ▄▄  █▀ ▄ ▄▀▀██▄▀▀█▄████
████▄▄▄▄▄▄▄█▄█▄▄▄▄▄█▄▄▄▄█▄█▄▄█▄███▄█▄▄██▄▄█▄▄███▄██▄▄████
█████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████
PEER 2 QR code:
█████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████
████ ▄▄▄▄▄ █▀▄ ▄▀▄▄ ▄ ██ ▀▄▀▄█▄ ▀ █▀█ █▀█▀▀▀ █ ▄▄▄▄▄ ████
████ █   █ █▄▀▀ ▀ █ ▄▀▄ █▀  ▄▀█▄ ▀▄▄ ██ █▀█ ▄█ █   █ ████
████ █▄▄▄█ █ █ █ █   ▄▄▀█▄ ▄▄▄  ▀██   █▀ ▀▀███ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ ▀ █▄█ █▄▀ ▀ ▀ █▄█ ▀ █▄▀▄█ ▀▄▀▄█▄█▄▄▄▄▄▄▄████
████▄ ▀ ▀█▄▄▀ █▄ ▄█▀▄  ▄ ▀ ▄   ▀ ▄▀▀█▀█▀ ▀ ▄█▀▄▄ █▄▄█████
████ █ ▀█ ▄▀▀ █▀ ▀█▄█▄▀▀█ ██▄  ▀██▄▀  ▄ ▄▀ █▄█▄▀ ██▄ ████
████▀▀▀█  ▄█▀█▀ █▄█   █▄▄   █▀▀▄▀▀▄██▄▄▀█▀▄ ▀▄▄▄ █▀▄ ████
█████▀  ▄▀▄▄██ ▄ ▄▀ ▄██ █▀█▄▀▀▄▄█▄█ ▀█▄▄▄▄█▀▄▄█▀▄ ▀▀ ████
████▄█ ▄▄▀▄█ ▀▄▄█ ▄   █▄▄▀█▄▀▄▄▄ ▀▀ ▀█ ▄ ▄▀▀█▀▀▀▄▄█ ▀████
████▀▀█▀▀█▄█▄█▄█ ▀▄▄ █▄▀▄  ▀▄▄██▄ ▀█  █▄▄▀ ▀▀▄█▄▄▄ ▀█████
████ ▄▄█▀ ▄ █  ▀ ███ ▄▄█▀ █▀█ ▄██▀▄▄▄  ▀██▄▀█▄▄██ █▀ ████
████▀▀▄█ ▄▄▄ █▄▄██ █ ██▄█▄ ▄▄▄ ▀█ █▀ █▄▀ █ ▄ ▄▄▄ ▀▄ ▄████
██████▀▄ █▄█ ▄▀ █ █▀██▀ ▄  █▄█ ▀▄▄█▀ ██▀▀▀█▀ █▄█ ▀ █▀████
█████▀ ▀▄ ▄▄▄ ▄█▀  ▀▄▀▀ ▀▄▄ ▄ ▄▀▄▀███▄▄█▄▄█    ▄ ██  ████
████ █▀▄█ ▄▄▀ ▄▄ ▀▀ █▄█  ▀▀█▄▀ ▄█▄ ▄▀▄▀▀ ▀ ▄▄▄ ▄█▀▄▄▄████
████  █▄█ ▄█▄█▄▄▄█▄  █▀█▄▀▀ ███████▄▀  ██▀▄████▀█▄█▄ ████
████ █ ███▄▄▀ ▄█▀▀ ▀▀  ▄▀▄ ▄▀▀▀█ ▄██▀ ▀  █ ██▀▄▄█▄▄▄█████
█████▀████▄▀▀▄▄▀ ▄ ▀█▀▄▀ ▄█▀▄▀█▄▀ ▄ ▄▀ ▄▄█▀▀█  █ █▄█▀████
████ ▀▀█  ▄ ▀ ██ ▀▄█▄█▄█▀█▀█▀█▄█▀▄ ▀▄ ▄██ ▄█    ▄▀▀▄▄████
█████ ▀▀█▄▄▄▄██▄▀▄██▀ ▄▀█▀▄ █▄▄ ▄▄▄ █▀▄ ▄███▀▀▀██▀██▄████
████▄▄▄███▄▄▀▀▄██  ▄█▄▀ ▄█ ▄▄▄ ██▀█▄█▄▄█▀▄██ ▄▄▄ ▀█▄▄████
████ ▄▄▄▄▄ █▄▄▀██▄▀▄  ▀▀▄█ █▄█ ▄ █ ▀▄▄ ▄ ███ █▄█ ▄  ▀████
████ █   █ █▀▄ ▀▄ ▄ ▄▀█▀█▄  ▄ ▄███ █▄▄ ▄▀█▀▀▄ ▄  ▀██▄████
████ █▄▄▄█ █▀▀▄▄▄█▄ █▄▄▀▀▀█▄█▀▀██ ▄▄  █▀ ▄ ▄▀▀██▄▀▀█▄████
████▄▄▄▄▄▄▄█▄▄█▄▄▄▄█▄▄▄▄█▄█▄▄█▄███▄█▄▄██▄▄█▄▄███▄██▄▄████
█████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
./run: line 10: wg-quick: command not found
[services.d] done.
.:53
CoreDNS-1.6.9
linux/arm, go1.14.1, 1766568
```

**Comment by aptalca** [comment]
Your have dns/networking issues on your docker host. The container can't even read the ubuntu repos.

**Comment by The-Kid-Gid** [comment]
Thank you. I just realized my pihole dns _might_ be the issue.

**Comment by The-Kid-Gid** [comment]
Fixed! I could not get Raspbian to work, and I switched to Ubuntu Server.

**Comment by AdySan** [comment]
@The-Kid-Gid I had the same problem and fixed it the same way. When connected to the server, can you access other computers on the network by the hostname? something like `mylaptop.local`, I can address by IP address just fine, but would be great to use hostnames.

**Comment by aptalca** [comment]
you need to set your dns correctly for lan host name resolution

**Comment by The-Kid-Gid** [comment]
@AdySan I do not have local domains set up.

**Comment by AdySan** [comment]
> you need to set your dns correctly for lan host name resolution

Thanks @aptalca, where do I do that. Tried setting the PEERDNS and also in the wireguard app on iPhone. Neither can I address by host name, and I still get ads, so it’s not using the PiHole nor my router (which points to the PiHole for DNS)
